name: Start new release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release type
        default: next
        required: true
        options:
        - next
        - patch
        - publish
      base-ref:
        description: Base version
        default: master
        required: false

env:
  HUSKY: 0

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.CI_PAT }}

    - name: Setup NodeJS
      uses: ./.github/actions/setup-node
      with:
        node-version: 14.21.3
        cache-modules: true
        install: true

    - uses: dtinth/setup-github-actions-caching-for-turbo@v1

    - name: Build
      run: yarn build --filter=@rocket.chat/release-action

    - name: Start next release
      if: ${{ github.event.inputs.name == 'next' }}
      uses: ./packages/release-action
      with:
        action: bump
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CI_PAT }}

    - name: Start patch release
      if: ${{ github.event.inputs.name == 'patch' }}
      uses: ./packages/release-action
      with:
        action: patch
        base-ref: ${{ github.event.inputs.base-ref }}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CI_PAT }}

    - name: Publish release
      if: ${{ github.event.inputs.name == 'publish' }}
      uses: ./packages/release-action
      with:
        action: publish
        base-ref: ${{ github.event.inputs.base-ref }}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CI_PAT }}
