name: Publish Final Release

on:
  push:
    branches:
      - release-automation

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 14.21.3
          cache-modules: true
          install: true

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build
        run: yarn build --filter=@rocket.chat/release-action

      - name: Publish final release
        uses: ./packages/release-action
        with:
          action: publish-final
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
